### ISSUE TITLE
can't reproduce the results in your papers

### ISSUE THREAD

**Issue by Qingfeng-Yao** [ThomasK427/GCN-GAN-pytorch#1]
I find my results using given data and codes are different from your results presented in your paper. And I can't find the use of GAN can improve the performance.

**Comment by neighbourbasedrec** [comment]
+ 1 can't reproduce the results in the paper as well.

**Comment by yinyanting** [comment]
There are errors in preprocess.py,  firstly.  You incorrectly divided the datas. 
And there are lots of errors in parameter settings.
And the loss function is wrong.

You may need check your files carfully!

**Comment by Lee3Paul** [comment]
Can't reproduce the results as well. Could you please provide the proper parameter settings and correct codes that can reproduce the results in your paper on UCSB dataset? THANKS A LOT

**Comment by KuroginQin** [comment]
Please note that this code isn't the version provided by the original author of the paper. In fact, it's just the practice of some other people trying to implement the model.  Some key steps aren't taken in this implementation, including the (1) normalization and re-normalization of edge weights for the input and output, (2) the reshaping of the GCN feature output to a long vector, etc. Although (2) may significantly increase the complexity,  it's necessary, because TLP for dynamic weighted graphs is a hard graph-level problem, but GCN is originally designed to extract the node-level features to support node-level graph inference. Moreover, the training process is also different from the description in the paper, where the model parameters need to be continuously updated when it comes to a new timeslice.
  Some improvements can also be made to reduce the complexity, e.g., (1) combining the pre-training loss (minimization of reconstruction error) and GAN loss of G into one objective, which merges the pre-training and formal training into one step; (2) using additional FC layer to reduce the dimension of the long reshaped vectors before fedding it into RNN, etc.
    Some papers follow GCN-GAN and made some improvements, e.g., Yang et al. An Advanced Deep Generative Framework for Temporal Link Prediction in Dynamic Networks, IEEE Trans. on Cybernetics, etc.

**Comment by w2cxx0723** [comment]
你好在跑这个代码时，train.py文件运行报错："Traceback (most recent call last):
  File "D:\pycharm\Project\LNG_networks\GCN-GAN-pytorch-master\train2.py", line 102, in <module>
    generator_loss.backward()
  File "D:\pycharm\Project\venv\lib\site-packages\torch\_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "D:\pycharm\Project\venv\lib\site-packages\torch\autograd\__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [512, 1]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
"这是为什么呢？求大神指点，阿里嘎多！！！

**Comment by KuroginQin** [comment]
> 你好在跑这个代码时，train.py文件运行报错："Traceback (most recent call last): File "D:\pycharm\Project\LNG_networks\GCN-GAN-pytorch-master\train2.py", line 102, in generator_loss.backward() File "D:\pycharm\Project\venv\lib\site-packages\torch_tensor.py", line 487, in backward torch.autograd.backward( File "D:\pycharm\Project\venv\lib\site-packages\torch\autograd__init__.py", line 200, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [512, 1]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True). "这是为什么呢？求大神指点，阿里嘎多！！！

This is not the official implementation. Follows are FIY.

https://github.com/yanghaoxie/GCN-GAN-for-Weighted-Dynamic-Networks
https://github.com/KuroginQin/OpenTLP
